version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - network

  web:
    image: your-apache-php-image
    ports:
      - 80:80
    volumes:
      - ./your-web-app:/var/www/html
      - ./apache-config:/etc/apache2/sites-available
      - ./logs:/var/log/apache2
    networks:
      - network
    depends_on:
      - db

volumes:
  db_data:
  apache-config:
  logs:

networks:
  network:
