version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    container_name: my-apache-php-container
    image: my-apache-php-image
    volumes:
      - ./html:/var/www/html
      - ./config:/etc/apache2/sites-available
      - ./logs:/var/log/apache2
    networks:
      - network

networks:
  network:
