- name: Instances
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 5m
    labels:
      severity: page
    # Prometheus templates apply here in the annotation and label fields of the alert.
    annotations:
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes.'
      summary: 'Instance {{ $labels.instance }} down'

  - alert: AlertmanagerNotificationsFailing
    expr: rate(alertmanager_notifications_failed_total[1m]) > 0
    labels:
      pager: pagerduty
      service: alertmanager
      severity: critical
    annotations:
      title: Alertmanager is failing sending notications
      runbook: troubleshooting/alertmanager-notification-failures.md
      description: Alertmanager is seeing errors for integration {{$labels.integration}}

  - alert: NodeSwapUsage
    expr: (((node_memory_SwapTotal-node_memory_SwapFree)/node_memory_SwapTotal)*100) > 75
    for: 2m
    labels:
      severity: "warning"
    annotations:
      summary: "{{$labels.instance}}: Swap usage detected"
      description: "{{$labels.instance}}: Swap usage usage is above 75% (current value is: {{ $value }})"
  - alert: NodeMemUsage
    expr: (((node_memory_MemTotal-node_memory_MemFree-node_memory_Cached)/(node_memory_MemTotal)*100)) > 75
    for: 2m
    labels:
      severity: "crirical"
    annotations:
      summary: "{{$labels.instance}}: Mem usage detected"
      description: "{{$labels.instance}}: Memory usage is above 75% (current value is: {{ $value }})"

  - alert: Down HTTP Service
    expr: node_systemd_unit_state{name="httpd.service",state="active"} == 0
    for: 30s
    labels:
      severity: "critical"
      job: Web-Service
    annotations:
      summary: "{{$labels.instance}}: Webservice service Failed"
      description: "{{$labels.instance}}: webservice Service Failed: {{ $value }})"

#  - alert: DailyTest
#    expr: vector(1) > 0
#    for: 1m
#    labels:
#      job: dailytest
#    annotations:
#      summary: "daily alert test"
#      description: "daily alert test"
#

  - alert: CPU_Threshold_Exceeded
    expr: (100 * (1 - avg by(instance)(irate(node_cpu{mode='idle'}[1h])))) > 90
    for: 1h
    labels:
      severity: "critical"
    annotations:
      summary: "Instance {{ $labels.instance }} CPU usage is dangerously high"
      description: "This device's CPU usage has exceeded the thresold of 90% with a value of {{ $value }} for 1 hour."
  - alert: Instance_Low_Memory
    expr:  node_memory_MemAvailable < 268435456
    for: 10m
    labels:
      severity: "critical"
    annotations:
      summary: "Instance {{ $labels.instance }}: memory low "
      description:  "{{$labels.instance}} has less than 256M memory available"
  - alert: Disk_USAGE_Thresold_Exceeded
    expr:  node_filesystem_free{fstype!~"rootfs|tmpfs|fuse.lxcfs"} / node_filesystem_size{fstype!~"rootfs|tmpfs|fuse.lxcfs"} < 0.10
    for: 15m
    labels:
      severity: "warning"
    annotations:
      summary: "Instance {{$labels.instance}}: disk {{$labels.instance}} filling up"
      description: "{{$labels.device}} mounted on {{$labels.mountpoint}} on {{$labels.instance}} is 90% filled."


