{
 "title": "SYSTEM",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "intervel",
    "label": "intervel",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "server",
    "label": "Host",
    "query": "label_values(node_boot_time_seconds, instance)"
   },
   {
    "name": "mointpiont",
    "label": "Mount",
    "query": "label_values(node_filesystem_avail_bytes{instance=\"$server\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}, mountpoint)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<h1><i><font color=#5991A7><b><center>System Overview for </font><font color=#e68a00>$server</font> <font color=#5991A7> with</font> </font><font color=#e68a00>$intervel</font> <font color=#5991A7>resolution</center></b></font></i></h1>"
  },
  {
   "title": "$server - Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 2 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$server\"} - node_boot_time_seconds{instance=~\"$server\"}"
    }
   ]
  },
  {
   "title": "$server-state",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 19, "x": 5, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{instance=~\"$server\",job=~\"linux systems\"}"
    }
   ]
  },
  {
   "title": "$server - System_State",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{instance=~\"$server\",job=~\"linux systems\"}",
     "legendFormat": "Up / Down"
    }
   ]
  },
  {
   "title": "$server - Login_Count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_logind_sessions{instance=~\"$server\",type!~\"unspecified\"})",
     "legendFormat": "login"
    }
   ]
  },
  {
   "title": "$server - Login",
   "type": "graph",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_logind_sessions{type=\"tty\", class=\"user\",seat!=\"seat0\", remote=\"true\", instance=~\"$server\"}",
     "legendFormat": "Remote Login"
    },
    {
     "expr": "node_logind_sessions{type=\"x11\", class=\"user\",seat!=\"seat0\", remote=\"true\", instance=~\"$server\"}",
     "legendFormat": "Console Login"
    },
    {
     "expr": "node_logind_sessions{class=\"user\",remote=\"true\",type=\"cron\", instance=~\"$server\"}",
     "legendFormat": "Login_Session"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 17 },
   "content": "<h1><i><font color=#5991A7><b><center>Network Spec </font><font color=#e68a00>$server</font> <font color=#5991A7> with</font> </font><font color=#e68a00>$intervel</font> <font color=#5991A7>resolution</center></b></font></i></h1>"
  },
  {
   "title": "$server - Network I/P Speed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 19 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": " sum(rate(node_network_receive_bytes_total{device!=\"lo\",instance=\"$server\"}[$intervel])) or sum(rate(node_network_receive_bytes_total{device!=\"lo\",instance=\"$server\"}[5m]))"
    }
   ]
  },
  {
   "title": "$server - Listening State",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_tcp_connection_states{instance=~\"$server\",state=\"listen\"})"
    }
   ]
  },
  {
   "title": "$server - Syn Recv State",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_tcp_connection_states{instance=~\"$server\",state=\"syn_recv\"}"
    }
   ]
  },
  {
   "title": "$server - Establish State",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_tcp_connection_states{instance=~\"$server\",state=\"established\"}"
    }
   ]
  },
  {
   "title": "$server - Fin Wait1 State",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_tcp_connection_states{instance=~\"$server\",state=\"fin_wait1\"}"
    }
   ]
  },
  {
   "title": "$server - Fin Wait2 State",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_tcp_connection_states{instance=~\"$server\",state=\"fin_wait2\"}"
    }
   ]
  },
  {
   "title": "$server - Network  O/P Speed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 23 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device!=\"lo\",instance=~\"$server\"}[$intervel])) or sum(rate(node_network_transmit_bytes_total{device!=\"lo\",instance=~\"$server\"}[5m])) "
    }
   ]
  },
  {
   "title": "$server - Last Ack State",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_tcp_connection_states{instance=~\"$server\",state=\"last_ack\"}"
    }
   ]
  },
  {
   "title": "$server - Close wait State",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_tcp_connection_states{instance=~\"$server\",state=\"close_wait\"}"
    }
   ]
  },
  {
   "title": "$server - Time Wait State",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_tcp_connection_states{instance=~\"$server\",state=\"time_wait\"}"
    }
   ]
  },
  {
   "title": "$server - Closing State",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_tcp_connection_states{instance=~\"$server\",state=\"closing\"}"
    }
   ]
  },
  {
   "title": "$server - Sync Sent State",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_tcp_connection_states{instance=~\"$server\",state=\"sync_sent\"}"
    }
   ]
  },
  {
   "title": "$server - Sockets TCP/UDP connection state",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_tcp_connection_states{instance=~\"$server\",state=\"established\"}",
     "legendFormat": "Establish_connection"
    },
    {
     "expr": "node_tcp_connection_states{instance=~\"$server\",state=\"listen\"}",
     "legendFormat": "Listen_connection"
    },
    {
     "expr": "node_tcp_connection_states{instance=~\"$server\",state=\"last_ack\"}",
     "legendFormat": "Last_ack_connection"
    },
    {
     "expr": "node_tcp_connection_states{instance=~\"$server\",state=\"fin_wait1\"}",
     "legendFormat": "Fin_wait1_connection"
    },
    {
     "expr": "node_tcp_connection_states{instance=~\"$server\",state=\"fin_wait2\"}",
     "legendFormat": "Fin_wait2_connection"
    },
    {
     "expr": "node_tcp_connection_states{instance=~\"$server\",state=\"syn_recv\"}",
     "legendFormat": "Sync_connection"
    },
    {
     "expr": "node_tcp_connection_states{instance=~\"$server\",state=\"closing\"}",
     "legendFormat": "closing_connection"
    },
    {
     "expr": "node_sockstat_UDPLITE_inuse{instance=~\"$server\"}",
     "legendFormat": "UDPLITE_inuse"
    },
    {
     "expr": "node_sockstat_RAW_inuse{instance=~\"$server\"}",
     "legendFormat": "RAW_inuse"
    },
    {
     "expr": "node_sockstat_FRAG_inuse{instance=~\"$server\"}",
     "legendFormat": "FRAG_inuse"
    },
    {
     "expr": "node_tcp_connection_states{instance=~\"$server\",state=\"time_wait\"}",
     "legendFormat": "time_wait Connection"
    }
   ]
  },
  {
   "title": "$server - Process Forks state",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " irate(node_forks_total{instance=~\"$server\"}[$intervel]) or rate(node_forks_total{instance=~\"$server\"}[1m])",
     "legendFormat": "process_forks_state"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 43 },
   "content": "<h1><i><font color=#5991A7><b><center>System Spec </font><font color=#e68a00>$server</font> <font color=#5991A7> with</font> </font><font color=#e68a00>$intervel</font><font color=#5991A7> resolution</center></b></font></i></h1>"
  },
  {
   "title": "$server - CPU Count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 45 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$server\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "$server - Cpu",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 45 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$server\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$server\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$server\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "$server - Virtual Memory",
   "type": "singlestat",
   "description": "Ram + swap",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 45 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$server\"}+node_memory_SwapTotal_bytes{instance=~\"$server\"}"
    }
   ]
  },
  {
   "title": "$server - RAM",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 45 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$server\"}"
    }
   ]
  },
  {
   "title": "$server - RAM Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 45 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=~\"$server\"} - node_memory_MemFree_bytes{instance=~\"$server\"})  / (node_memory_MemTotal_bytes{instance=~\"$server\"})) * 100 "
    }
   ]
  },
  {
   "title": "$server - Disk Space",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 50 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg(node_filesystem_size_bytes{instance=~\"$server\",fstype=~\"(ext.|xfs|vfat)\"}) without (mountpoint)) without (device,fstype)"
    }
   ]
  },
  {
   "title": "$server - Disk Free",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 50 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(node_filesystem_free_bytes{instance=~\"$server\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay\"}/node_filesystem_size_bytes{instance=~\"$server\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay\"})*100"
    }
   ]
  },
  {
   "title": "$server - Root Size",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 50 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$server\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "$server - Root Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 50 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$server\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\"$server\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "$server - Memory Available",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 50 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(node_memory_MemAvailable_bytes{instance=~\"$server\"} or (node_memory_MemFree_bytes{instance=~\"$server\"} + node_memory_Buffers_bytes{instance=~\"$server\"} + node_memory_Cached_bytes{instance=~\"$server\"})) / node_memory_MemTotal_bytes{instance=~\"$server\"} * 100"
    }
   ]
  },
  {
   "title": "$server - Load Average 1m",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 55 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(node_load1{instance=\"$server\"}[$intervel]) or avg_over_time(node_load1{instance=\"$server\"}[5m])"
    }
   ]
  },
  {
   "title": "$server - Load Average 5m",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 55 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(node_load5{instance=\"$server\"}[$intervel]) or avg_over_time(node_load5{instance=\"$server\"}[5m])"
    }
   ]
  },
  {
   "title": "$server - Load Average 15m",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 55 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(node_load15{instance=\"$server\"}[$intervel]) or avg_over_time(node_load15{instance=\"$server\"}[5m])"
    }
   ]
  },
  {
   "title": "$server - Swap Size",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 55 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=~\"$server\"}"
    }
   ]
  },
  {
   "title": "$server - Swap Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 55 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=~\"$server\"} - node_memory_SwapFree_bytes{instance=~\"$server\"})  / (node_memory_SwapFree_bytes{instance=~\"$server\"})) * 100 "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 60 },
   "content": "<h1><i><font color=#5991A7><b><center>DRBD STATUS </font><font color=#e68a00>$server</font> <font color=#5991A7> with</font> </font><font color=#e68a00>$intervel</font><font color=#5991A7> resolution</center></b></font></i></h1>"
  },
  {
   "title": "$server - DRBD Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 13, "x": 0, "y": 62 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_drbd_connected{instance=\"$server\"})"
    }
   ]
  },
  {
   "title": "$server - DRBD Role",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 11, "x": 13, "y": 62 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_drbd_node_role_is_primary{instance=\"$server\",node=\"local\"})"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 65 },
   "content": "<h1><i><font color=#5991A7><b><center>Load  </font><font color=#e68a00>$server</font> <font color=#5991A7> with</font> </font><font color=#e68a00>$intervel</font><font color=#5991A7> resolution</center></b></font></i></h1>"
  },
  {
   "title": "$server - Load Average",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server\"}",
     "legendFormat": "LoadAvg 1m"
    },
    {
     "expr": "node_load5{instance=~\"$server\"}",
     "legendFormat": "LoadAvg 5m"
    },
    {
     "expr": "node_load15{instance=~\"$server\"}",
     "legendFormat": "LoadAvg 15m"
    }
   ]
  },
  {
   "title": "$server - system load ($intervel)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_load1{instance=~\"$server\"}[5m]) or irate(node_load1{instance=~\"$server\"}[$intervel])",
     "legendFormat": "load1"
    },
    {
     "expr": "rate(node_load5{instance=~\"$server\"}[5m]) or irate(node_load5{instance=~\"$server\"}[$intervel])",
     "legendFormat": "load5"
    },
    {
     "expr": "rate(node_load15{instance=~\"$server\"}[5m]) or irate(node_load15{instance=~\"$server\"}[$intervel])",
     "legendFormat": "load15"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 79 },
   "content": "<h1><i><font color=#5991A7><b><center>Data for </font><font color=#e68a00>$server</font> <font color=#5991A7> with </font> </font><font color=#e68a00> $intervel </font> <font color=#5991A7>CPU Usages</center></b></font></i></h1>"
  },
  {
   "title": "All Cores - total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 81 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(sum by () ((avg by (mode) ( \n(clamp_max(rate(node_cpu_seconds_total{instance=\"$server\",mode!=\"idle\",mode!=\"iowait\"}[$intervel]),1)) or \n(clamp_max(irate(node_cpu_seconds_total{instance=\"$server\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )) *100 or \nsum by () (\navg_over_time(node_cpu_average{instance=\"$server\",mode!=\"total\",mode!=\"idle\"}[$intervel]) or \navg_over_time(node_cpu_average{instance=\"$server\",mode!=\"total\",mode!=\"idle\"}[5m])) unless\n(avg_over_time(node_cpu_average{instance=\"$server\",mode=\"total\",job=\"rds-basic\"}[$intervel]) or \navg_over_time(node_cpu_average{instance=\"$server\",mode=\"total\",job=\"rds-basic\"}[5m]))\n),100)"
    }
   ]
  },
  {
   "title": "All Cores - user",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 81 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"$server\",mode=\"user\"}[$intervel]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"$server\",mode=\"user\"}[5m]),1)) )) *100 or (avg_over_time(node_cpu_average{instance=\"$server\", mode=\"user\"}[$intervel]) or avg_over_time(node_cpu_average{instance=\"$server\", mode=\"user\"}[5m]))),100)"
    }
   ]
  },
  {
   "title": "All Cores - system",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 81 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"$server\",mode=\"system\"}[$intervel]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"$server\",mode=\"system\"}[5m]),1)) )) *100 or (avg_over_time(node_cpu_average{instance=\"$server\", mode=\"system\"}[$intervel]) or avg_over_time(node_cpu_average{instance=\"$$server\", mode=\"system\"}[5m]))),100)"
    }
   ]
  },
  {
   "title": "All Cores - system",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 81 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"$server\",mode=\"system\"}[$intervel]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"$server\",mode=\"system\"}[5m]),1)) )) *100 or (avg_over_time(node_cpu_average{instance=\"$server\", mode=\"system\"}[$intervel]) or avg_over_time(node_cpu_average{instance=\"$$server\", mode=\"system\"}[5m]))),100)"
    }
   ]
  },
  {
   "title": "All Cores - Other",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 81 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(((sum by () (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"$server\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"steal\"}[$intervel]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"$server\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"steal\"}[5m]),1)) )) *100) or (sum(avg_over_time(node_cpu_average{instance=\"$server\", mode!=\"total\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"wait\",mode!=\"steal\"}[$intervel])) or sum(avg_over_time(node_cpu_average{instance=\"$server\", mode!=\"total\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"wait\",mode!=\"steal\"}[5m])))),100) "
    }
   ]
  },
  {
   "title": "All Cores - steal",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 81 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"$server\",mode=\"steal\"}[$intervel]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"$server\",mode=\"steal\"}[5m]),1)) )) *100 or (avg_over_time(node_cpu_average{instance=\"$server\", mode=\"steal\"}[$intervel]) or avg_over_time(node_cpu_average{instance=\"$server\", mode=\"steal\"}[5m]))),100)"
    }
   ]
  },
  {
   "title": "$server - Overall CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"$server\",mode!=\"idle\"}[$intervel]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"$server\",mode!=\"idle\"}[5m]),1)) ))*100 or (max_over_time(node_cpu_average{instance=~\"$server\", mode!=\"total\", mode!=\"idle\"}[$intervel]) or max_over_time(node_cpu_average{instance=~\"$server\", mode!=\"total\", mode!=\"idle\"}[5m]))),100)",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "clamp_max(max by () ((sum  by (cpu) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"$server\",mode!=\"idle\",mode!=\"iowait\"}[$intervel]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"$server\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )*100) or (max_over_time(node_cpu_average{instance=~\"$server\", mode!=\"total\", mode!=\"idle\", mode!=\"wait\"}[$intervel]) or max_over_time(node_cpu_average{instance=~\"$server\", mode!=\"total\",mode!=\"idle\", mode!=\"wait\"}[5m]))),100)",
     "legendFormat": "Max Core Utilization"
    }
   ]
  },
  {
   "title": "$server - Current CPU Core Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "clamp_max(avg by () ((sum by (cpu) ( (clamp_max(irate(node_cpu_seconds_total{instance=\"$server\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1))*100 )) or max_over_time(node_cpu_average{instance=~\"$server\", mode!=\"total\",mode!=\"idle\", mode!=\"wait\"}[5m])) ,100)",
     "legendFormat": "Avg"
    },
    {
     "expr": "clamp_max((sum by (cpu) ( (clamp_max(irate(node_cpu_seconds_total{instance=\"$server\",mode!=\"idle\",mode!=\"iowait\"}[5m])*100,100)) )) or sum by (cpu) (max_over_time(node_cpu_average{instance=~\"$server\", mode!=\"total\",mode!=\"idle\", mode!=\"wait\"}[5m])) ,100)",
     "legendFormat": " {{cpu}}"
    }
   ]
  },
  {
   "title": "$server - CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{instance=\"$server\",mode=\"idle\"}[1m])) by (instance)) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$server - Saturation Metrics",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(avg_over_time(node_procs_running{instance=~\"$server\"}[$intervel])-1) / scalar(count(node_cpu_seconds_total{instance=~\"$server\"}))",
     "legendFormat": "Normalized_CPU_Load"
    },
    {
     "expr": "avg_over_time(node_procs_blocked{instance=~\"$server\"}[$intervel]) or avg_over_time(node_procs_blocked{instance=~\"$server\"}[5m]) ",
     "legendFormat": "IO_Load "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 111 },
   "content": "<h1><i><font color=#5991A7><b><center>Data for </font><font color=#e68a00>$server</font> <font color=#5991A7> with </font> </font><font color=#e68a00> $intervel </font> <font color=#5991A7>Memory Usages</center></b></font></i></h1>"
  },
  {
   "title": "$server - Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "percent", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "100*(node_memory_MemTotal_bytes{instance=~\"$server\"} - node_memory_MemFree_bytes{instance=~\"$server\"} - node_memory_Buffers_bytes{instance=~\"$server\"} - node_memory_Cached_bytes{instance=~\"$server\"}) / node_memory_MemTotal_bytes{instance=~\"$server\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$server - Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$server\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$server\"}",
     "legendFormat": "Buffer"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$server\"}",
     "legendFormat": "Cache"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$server\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$server\"} - (node_memory_MemAvailable_bytes{instance=~\"$server\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "$server - Memory Stack",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 124 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$server\"} - node_memory_MemFree_bytes{instance=~\"$server\"} - node_memory_Buffers_bytes{instance=~\"$server\"} - node_memory_Cached_bytes{instance=~\"$server\"} - node_memory_Slab_bytes{instance=~\"$server\"} - node_memory_PageTables_bytes{instance=~\"$server\"} - node_memory_SwapCached_bytes{instance=~\"$server\"}",
     "legendFormat": "Apps - Memory used by user-space applications"
    },
    {
     "expr": "node_memory_PageTables_bytes{instance=~\"$server\"}",
     "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
    },
    {
     "expr": "node_memory_SwapCached_bytes{instance=~\"$server\"}",
     "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
    },
    {
     "expr": "node_memory_Slab_bytes{instance=~\"$server\"}",
     "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$server\"}",
     "legendFormat": "Cache - Parked file data (file content) cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$server\"}",
     "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$server\"}",
     "legendFormat": "Unused - Free memory unasigned"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"$server\"} - node_memory_SwapFree_bytes{instance=~\"$server\"})",
     "legendFormat": "Swap - Swap space used"
    },
    {
     "expr": "node_memory_HardwareCorrupted_bytes{instance=~\"$server\"}",
     "legendFormat": "Harware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
    }
   ]
  },
  {
   "title": "$server - Memory Commited",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 134 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Committed_AS_bytes{instance=~\"$server\"}",
     "legendFormat": "Committed_AS - Amount of memory presently allocated on the system"
    },
    {
     "expr": "node_memory_CommitLimit_bytes{instance=~\"$server\"}",
     "legendFormat": "CommitLimit - Amount of  memory currently available to be allocated on the system"
    }
   ]
  },
  {
   "title": "$server - Memory Active/Inactive",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 141 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Inactive_bytes{instance=~\"$server\"}",
     "legendFormat": "Inactive - Memory which has been less recently used.  It is more eligible to be reclaimed for other purposes"
    },
    {
     "expr": "node_memory_Active_bytes{instance=~\"$server\"}",
     "legendFormat": "Active - Memory that has been used more recently and usually not reclaimed unless absolutely necessary"
    }
   ]
  },
  {
   "title": "$server - Swap Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 149 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=~\"$server\"} - node_memory_SwapFree_bytes{instance=~\"$server\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_SwapFree_bytes{instance=~\"$server\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{instance=~\"$server\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 158 },
   "content": "<h1><i><font color=#5991A7><b><center>Data for </font><font color=#e68a00>$server</font> <font color=#5991A7> with </font> </font><font color=#e68a00> $intervel </font> <font color=#5991A7>Network Usages </center></b></font></i></h1>"
  },
  {
   "title": "$server - Network Traffic - 1m",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 160 },
   "yaxes": [
    { "format": "Bps", "label": "bits out (-) / bits in (+)" }
   ],
   "targets": [
    {
     "expr": "sum (irate(node_network_receive_bytes_total{instance=~\"$server\", device!~\"lo|virbr0|virbr0-nic\"}[1m])) by (instance) > 0",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum (irate(node_network_transmit_bytes_total{instance=~\"$server\", device!~\"lo|virbr0|virbr0-nic\"}[1m])) by (instance) > 0",
     "legendFormat": "outbound"
    }
   ]
  },
  {
   "title": "$server - Network Traffic - 5m",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 170 },
   "yaxes": [
    { "format": "Bps", "label": "bits out (-) / bits in (+)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=\"$server\", device!=\"lo\"}[$intervel])) or \nsum(irate(node_network_receive_bytes_total{instance=\"$server\", device!=\"lo\"}[5m])) ",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{instance=\"$server\", device!=\"lo\"}[$intervel])) or \nsum(irate(node_network_transmit_bytes_total{instance=\"$server\", device!=\"lo\"}[5m])) ",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "$server - Network Utilization Hourly",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 179 },
   "repeat": "server",
   "yaxes": [
    { "format": "bytes", "label": "bits out (-) / bits in (+)" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{instance=~\"$server\", device!=\"lo\"}[1h]))",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{instance=~\"$server\", device!=\"lo\"}[1h]))",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "$server - Network Utilization last 24-Hour's",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 197 },
   "yaxes": [
    { "format": "bytes", "label": "bits out (-) / bits in (+)" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{instance=\"$server\", device!=\"lo\"}[1h]))",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{instance=\"$server\", device!=\"lo\"}[1h]))",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "$server - Network Traffic Basic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 206 },
   "yaxes": [
    { "format": "Bps", "label": "bits out (-) / bits in (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=~\"$server\",device!~\"lo\",device!~\"virbr0\",device!~\"virbr0-nic\"}[$intervel]) or rate(node_network_receive_bytes_total{instance=~\"$server\",device!~\"lo\",device!~\"virbr0\",device!~\"virbr0-nic\"}[5m])",
     "legendFormat": "{{device}}_Receive_Bytes"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{instance=~\"$server\",device!~\"lo\",device!~\"virbr0\",device!~\"virbr0-nic\"}[$intervel]) or rate(node_network_receive_bytes_total{instance=~\"$server\",device!~\"lo\",device!~\"virbr0\",device!~\"virbr0-nic\"}[5m]) ",
     "legendFormat": "{{device}}_Sent_Bytes"
    }
   ]
  },
  {
   "title": "$server - Network Packet",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 215 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_packets_total{instance=~\"$server\", device!=\"lo\",device!=\"virbr0\",device!=\"virbr0-nic\"}[$intervel]) or \nirate(node_network_receive_packets_total{instance=~\"$server\", device!=\"lo\",device!=\"virbr0\",device!=\"virbr0-nic\"}[5m])",
     "legendFormat": "{{device}}_receive"
    },
    {
     "expr": "rate(node_network_transmit_packets_total{instance=~\"$server\", device!=\"lo\",device!=\"virbr0\",device!=\"virbr0-nic\"}[$intervel]) or \nirate(node_network_transmit_packets_total{instance=~\"$server\", device!=\"lo\",device!=\"virbr0\",device!=\"virbr0-nic\"}[5m])",
     "legendFormat": "{{device}}_trans"
    }
   ]
  },
  {
   "title": "$server - Local Network Errors",
   "type": "graph",
   "description": "Total Number of Local Network Interface Transmit Errors, Receive Errors and Drops.  Should be  Zero",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 222 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_errs_total{instance=~\"$server\", device!=\"lo\"}[$intervel])) or sum(irate(node_network_receive_errs_total{instance=~\"$server\", device!=\"lo\"}[5m]))",
     "legendFormat": "Receive Errors"
    },
    {
     "expr": "sum(rate(node_network_transmit_errs_total{instance=~\"$host\", device!=\"lo\"}[$intervel])) or sum(irate(node_network_transmit_errs_total{instance=~\"$server\", device!=\"lo\"}[5m]))",
     "legendFormat": "Transmit Errors"
    },
    {
     "expr": "sum(rate(node_network_receive_drop_total{instance=~\"$server\", device!=\"lo\"}[$intervel])) or sum(irate(node_network_receive_drop_total{instance=~\"$server\", device!=\"lo\"}[5m]))",
     "legendFormat": "Receive Drop"
    },
    {
     "expr": "sum(rate(node_network_transmit_drop_total{instance=~\"$server\", device!=\"lo\"}[$intervel])) or sum(irate(node_network_transmit_drop_total{instance=~\"$server\", device!=\"lo\"}[5m]))",
     "legendFormat": "Transmit Drop"
    }
   ]
  },
  {
   "title": "$server - TCP Retransmission",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 229 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Tcp_RetransSegs{instance=\"$server\"}[5m]) or rate(node_netstat_Tcp_RetransSegs{instance=\"$server\"}[$intervel])",
     "legendFormat": "Segments_Retransmitted"
    },
    {
     "expr": "rate(node_netstat_Tcp_RetransSegs{instance=\"$server\"}[$intervel]) / rate(node_netstat_Tcp_RetransSegs{instance=\"$server\"}[$intervel]) or irate(node_netstat_Tcp_RetransSegs{instance=\"$server\"}[5m])/ irate(node_netstat_Tcp_RetransSegs{instance=\"$server\"}[5m]) ",
     "legendFormat": "Retransmit _Ratio"
    }
   ]
  },
  {
   "title": "$server - TCP & UDP Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 238 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_sockstat_TCP_mem_bytes{instance=~\"$server\"}[5m]) or rate(node_sockstat_TCP_mem_bytes{instance=~\"$server\"}[$intervel])",
     "legendFormat": "TCP_Memory_bytes"
    },
    {
     "expr": "rate(node_sockstat_UDP_mem_bytes{instance=~\"$server\"}[5m]) or rate(node_sockstat_UDP_mem_bytes{instance=~\"$server\"}[$intervel])",
     "legendFormat": "UDP_Memory_bytes"
    }
   ]
  },
  {
   "title": "$server - UDP Stat",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 247 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Udp_OutDatagrams{instance=~\"$server\"}[5m]) or irate(node_netstat_Udp_OutDatagrams{instance=~\"$server\"}[$intervel])",
     "legendFormat": "Udp_OutDatagrams"
    },
    {
     "expr": "irate(node_netstat_Udp_InDatagrams{instance=~\"$server\"}[5m]) or irate(node_netstat_Udp_InDatagrams{instance=~\"$server\"}[$intervel])",
     "legendFormat": "Udp_InDatagrams"
    },
    {
     "expr": "irate(node_netstat_Udp_NoPorts{instance=~\"$server\"}[5m]) or irate(node_netstat_Udp_NoPorts{instance=~\"$server\"}[$intervel])",
     "legendFormat": "Udp_NoPorts"
    }
   ]
  },
  {
   "title": "$server - TCP/UDP Stat",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 253 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_sockstat_TCP_alloc{instance=~\"$server\"}",
     "legendFormat": "TCP_alloc"
    },
    {
     "expr": "node_sockstat_TCP_inuse{instance=~\"$server\"}",
     "legendFormat": "TCP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_mem{instance=~\"$server\"}",
     "legendFormat": "TCP_mem"
    },
    {
     "expr": "node_sockstat_TCP_orphan{instance=~\"$server\"}",
     "legendFormat": "TCP_orpan"
    },
    {
     "expr": "node_sockstat_UDP_inuse{instance=~\"$server\"}",
     "legendFormat": "UDP_inuse"
    },
    {
     "expr": "node_sockstat_UDP_mem{instance=~\"$server\"}",
     "legendFormat": "UDP_mem"
    }
   ]
  },
  {
   "title": "$server - Context Switches",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 260 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_context_switches_total{instance=~\"$server\"}[$intervel])  or irate(node_context_switches_total{instance=~\"$server\"}[5m])",
     "legendFormat": "Contact Switches"
    },
    {
     "expr": "(rate(node_context_switches_total{instance=~\"$server\"}[1m]) or irate(node_context_switches_total{instance=~\"$server\"}[5m])) / scalar(count(node_cpu_seconds_total{mode=\"user\", instance=~\"$server\"}))",
     "legendFormat": "Context Switches per Virtual CPU"
    },
    {
     "expr": "node_nf_conntrack_entries{instance=~\"$server\"} / node_nf_conntrack_entries_limit{instance=~\"$server\"}",
     "legendFormat": "Queue Used"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 269 },
   "content": "<h1><i><font color=#5991A7><b><center>Data for </font><font color=#e68a00>$server</font> <font color=#5991A7> with </font> </font><font color=#e68a00> $intervel </font> <font color=#5991A7>Process and File Description</center></b></font></i></h1>"
  },
  {
   "title": "$server - Process",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 271 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(avg_over_time(node_procs_running{instance=~\"$server\"}[5m]) -1) or (avg_over_time(node_procs_running{instance=~\"$server\"}[$intervel]) -1)",
     "legendFormat": "Runnable Processes"
    },
    {
     "expr": "avg_over_time(node_procs_blocked{instance=~\"$server\"}[5m]) or avg_over_time(node_procs_blocked{instance=~\"$server\"}[$intervel])",
     "legendFormat": "Blocked Processes"
    },
    {
     "expr": "rate(node_forks_total{instance=~\"$server\"}[5m]) or irate(node_forks_total{instance=~\"$server\"}[1m])",
     "legendFormat": "Created Processes (Forks)"
    }
   ]
  },
  {
   "title": "$server - Processes Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 280 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=~\"$server\"}",
     "legendFormat": "Processes virtual memory size in bytes"
    },
    {
     "expr": "process_resident_memory_bytes{instance=~\"$server\"}",
     "legendFormat": "Processes resident memory size in bytes"
    }
   ]
  },
  {
   "title": "$server - File Descriptors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 288 },
   "yaxes": [
    { "format": "none", "label": "Descriptors" }
   ],
   "targets": [
    {
     "expr": "process_max_fds{instance=~\"$server\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "process_open_fds{instance=~\"$server\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$server - Process Forks",
   "type": "graph",
   "description": "fork() creates a new process by duplicating the calling process.  The  new process is referred to as the child process.  The calling process  is referred to as the parent process.\n\n       The child process and the parent process run in separate memory   spaces.  At the time of fork() both memory spaces have the same     content.  Memory writes, file mappings  and un mappings        performed by one of the processes do not affect the  other.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 297 },
   "yaxes": [
    { "format": "short", "label": "Forks / sec" }
   ],
   "targets": [
    {
     "expr": "rate(node_forks_total{instance=~\"$server\"}[5m]) or rate(node_forks_total{instance=~\"$server\"}[$intervel]) ",
     "legendFormat": "Processes forks second"
    }
   ]
  },
  {
   "title": "$server - Global File Descriptors Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 305 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filefd_maximum{instance=\"$server\"}",
     "legendFormat": "Limit"
    },
    {
     "expr": "node_filefd_allocated{instance=\"$server\"}",
     "legendFormat": "Allocated"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 314 },
   "content": "<h1><i><font color=#5991A7><b><center>Data for </font><font color=#e68a00>$server</font> <font color=#5991A7> with </font> </font><font color=#e68a00> $intervel </font> <font color=#5991A7>Disk Space</center></b></font></i></h1>"
  },
  {
   "title": "$server - Mount Total_Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 316 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$server\",device!=\"rootfs\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "$server - Disk Space Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 323 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$server\",device!~'rootfs'} - node_filesystem_avail_bytes{instance=~\"$server\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "$server - Mount Free_Space",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 332 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=~\"$server\",device!=\"rootfs\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "$server - Top 5 FileSystems Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 342 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(5, 100 - (node_filesystem_free_bytes{instance=~\"$server\",fstype=~\"xfs|ext4\"} / node_filesystem_size_bytes{instance=~\"$server\",fstype=~\"xfs|ext4\"} * 100))",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 349 },
   "content": "<h1><i><font color=#5991A7><b><center>Data for </font><font color=#e68a00>$server</font> <font color=#5991A7> with </font> </font><font color=#e68a00> $intervel </font> <font color=#5991A7>Disk Input/Output</center></b></font></i></h1>"
  },
  {
   "title": "$server - Disk IO Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 351 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=~\"$server\",device!~'dm-[0-9]'}[$intervel])/1000 or irate(node_disk_io_time_seconds_total{instance=~\"$server\",device!~'dm-[0-9]'}[5m])/1000",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "$server - Disk Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 358 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{instance=~\"$server\",device!~'dm-[0-9]'}[$intervel])/1000 or \nirate(node_disk_read_time_seconds_total{instance=~\"$server\",device!~'dm-[0-9]'}[5m])/1000",
     "legendFormat": "Read: {{ device }}"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total{instance=~\"$server\",device!~'dm-[0-9]'}[$intervel])/1000 or \nirate(node_disk_write_time_seconds_total{instance=~\"$server\",device!~'dm-[0-9]'}[5m])/1000",
     "legendFormat": "Write: {{ device }}"
    }
   ]
  },
  {
   "title": "$server - I/O Usage Times",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 365 },
   "yaxes": [
    { "format": "iops", "label": "Milliseconds" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$server\",device!~\"dm-[0-9]\"}[5m]) or irate(node_disk_io_time_seconds_total{instance=~\"$server\",device!~\"dm-[0-9]\"}[$intervel])",
     "legendFormat": "{{device}} - Milliseconds spent doing I/Os"
    }
   ]
  },
  {
   "title": "$server - Disk Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 375 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "  (rate(node_disk_read_time_seconds_total{instance=~\"$server\",device!~'dm-[0-9]'}[1m]) / \n  rate(node_disk_reads_completed_total{instance=~\"$server\",device!~'dm-[0-9]'}[5m])) or \n  (irate(node_disk_read_time_seconds_total{instance=~\"$server\",device!~'dm-[0-9]'}[1m]) / \n  irate(node_disk_reads_completed_total{instance=~\"$server\",device!~'dm-[0-9]'}[5m]))",
     "legendFormat": "Read: {{ device }}"
    },
    {
     "expr": "(rate(node_disk_write_time_seconds_total{instance=~\"$server\",device!~'dm-[0-9]'}[1m]) / \nrate(node_disk_writes_completed_total{instance=~\"$server\",device!~'dm-[0-9]'}[5m])) or \n(irate(node_disk_write_time_seconds_total{instance=~\"$server\",device!~'dm-[0-9]'}[1m]) / \nirate(node_disk_writes_completed_total{instance=~\"$server\",device!~'dm-[0-9]'}[5m]))",
     "legendFormat": "Write: {{ device }}"
    }
   ]
  },
  {
   "title": "$server - Disk Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 383 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{instance=~'$server',device!~'dm-[0-9]'}[1m]) or irate(node_disk_reads_completed_total{instance=~'$server',device!~'dm-[0-9]'}[5m])",
     "legendFormat": "Read: {{ device }}"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{instance=~'$server',device!~'dm-[0-9]'}[1m]) or irate(node_disk_writes_completed_total{instance=~'$server',device!~'dm-[0-9]'}[5m])",
     "legendFormat": "Write: {{device }}"
    }
   ]
  },
  {
   "title": "$server - Disk Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 390 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=\"$server\",device!~'dm-[0-9]',device!~'sr0'}[1m]) or irate(node_disk_read_bytes_total{instance=\"$server\",device!~'dm-[0-9]',device!~'sr0'}[5m])",
     "legendFormat": "{{ device }}_Read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{instance=\"$server\",device!~'dm-[0-9]',device!~'sr0'}[1m]) or irate(node_disk_written_bytes_total{instance=\"$server\",device!~'dm-[0-9]',device!~'sr0'}[5m])",
     "legendFormat": "{{device }}_Write"
    }
   ]
  },
  {
   "title": "$server - Disk I/O Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 398 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_vmstat_pgpgin{instance=\"$server\"}[$intervel]) * 1024 or irate(node_vmstat_pgpgin{instance=\"$server\"}[5m]) * 1024",
     "legendFormat": "Page_In"
    },
    {
     "expr": "rate(node_vmstat_pgpgout{instance=\"$server\"}[$intervel]) * 1024 or irate(node_vmstat_pgpgout{instance=\"$server\"}[5m]) * 1024",
     "legendFormat": "Page_Out"
    }
   ]
  },
  {
   "title": "$server - I/O Usage Read / Write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 405 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$server\",device=~\"[a-z]*[a-z]\"}[5m]) or irate(node_disk_read_bytes_total{instance=~\"$server\",device=~\"[a-z]*[a-z]\"}[$intervel])",
     "legendFormat": "{{device}}_Successfully read bytes"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$server\",device=~\"[a-z]*[a-z]\"}[5m]) or irate(node_disk_write_time_seconds_total{instance=~\"$server\",device=~\"[a-z]*[a-z]\"}[$intervel])",
     "legendFormat": "{{device}} - Successfully written bytes"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 412 },
   "content": "<h1><i><font color=#5991A7><b><center>Data for </font><font color=#e68a00>$server</font> <font color=#5991A7> with </font> </font><font color=#e68a00> $intervel </font> <font color=#5991A7>Service State</center></b></font></i></h1>"
  },
  {
   "title": "$server - Apache",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 414 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(node_systemd_unit_state{instance=~\"$server\",name=\"httpd.service\",state=\"active\"}) == 1",
     "legendFormat": "Up"
    },
    {
     "expr": "count(node_systemd_unit_state{instance=~\"$server\",name=\"httpd.service\",state=\"active\"}) == 0",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "$server - MySQL",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 414 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(node_systemd_unit_state{instance=~\"$server\",name=\"mysqld.service\",state=\"active\"}) == 1"
    },
    {
     "expr": "count(node_systemd_unit_state{instance=~\"$server\",name=\"mysqld.service\",state=\"active\"}) == 0"
    }
   ]
  },
  {
   "title": "$server - FTP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 414 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(node_systemd_unit_state{instance=~\"$server\",name=\"vsftpd.service\",state=\"active\"}) == 1"
    },
    {
     "expr": "count(node_systemd_unit_state{instance=~\"$server\",name=\"vsftpd.service\",state=\"active\"}) == 0"
    }
   ]
  },
  {
   "title": "$server - SSH",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 414 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(node_systemd_unit_state{instance=~\"$server\",name=\"sshd.service\",state=\"active\"}) == 1",
     "legendFormat": "Up"
    },
    {
     "expr": "count(node_systemd_unit_state{instance=~\"$server\",name=\"ssshd.service\",state=\"active\"}) == 0",
     "legendFormat": "down"
    },
    {
     "expr": "count(node_systemd_unit_state{instance=~\"$server\",name=\"openssh-daemon.service\",state=\"active\"}) == 1"
    }
   ]
  },
  {
   "title": "$server - Crond",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 414 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(node_systemd_unit_state{instance=~\"$server\",name=\"crond.service\",state=\"active\"}) == 1",
     "legendFormat": "Up"
    },
    {
     "expr": "count(node_systemd_unit_state{instance=~\"$server\",name=\"crond.service\",state=\"active\"}) == 0",
     "legendFormat": "down"
    }
   ]
  },
  {
   "title": "$server - Node",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 414 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(node_systemd_unit_state{instance=~\"$server\",name=\"node_exporter.service\",state=\"active\"}) == 1",
     "legendFormat": "Up"
    },
    {
     "expr": "count(node_systemd_unit_state{instance=~\"$server\",name=\"node_exporter.service\",state=\"active\"}) == 0",
     "legendFormat": "down"
    }
   ]
  }
 ]
}