global:
  slack_api_url: "https://hooks.slack.com/services/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"

route:
  receiver: "slack-notifications"
  group_by: [alertname, datacenter, app]

receivers:
  - name: "slack-notifications"
    slack_configs:
    - send_resolved: true
    - channel: "#docker"
      title: '{{ .Status | toUpper }}{{ if eq .Status "firing" }} - {{ .Alerts.Firing | len }}{{ end }} |  ken-DOCKER '
      text: >-
        {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *State:* `{{ .Labels.severity }}`
          *Description:* {{ .Annotations.description }}
          *Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:>
          *Details:*
          {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
          {{ end }}
        {{ end }}

# templates:
#   - "/etc/alertmanager/templates/myorg.tmpl"
