FROM ubuntu:latest
RUN apt-get update && \
    apt-get install -y wget && \
    wget https://github.com/prometheus/alertmanager/releases/download/v0.23.0/alertmanager-0.23.0.linux-amd64.tar.gz && \
    tar -xvf alertmanager-0.23.0.linux-amd64.tar.gz && \
    mv alertmanager-0.23.0.linux-amd64/* /usr/local/bin/ && \
    rm -rf alertmanager-0.23.0.linux-amd64.tar.gz alertmanager-0.23.0.linux-amd64

RUN mkdir -p /etc/alertmanager/
COPY alertmanager/alertmanager.yml /etc/alertmanager/alertmanager.yml
EXPOSE 9093

CMD ["alertmanager", "--config.file=/etc/alertmanager/alertmanager.yml"]
