FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y wget && \
    wget https://github.com/prometheus/node_exporter/releases/download/v1.2.2/node_exporter-1.2.2.linux-amd64.tar.gz && \
    tar -xvf node_exporter-1.2.2.linux-amd64.tar.gz && \
    mv node_exporter-1.2.2.linux-amd64/* /usr/local/bin/ && \
    rm -rf node_exporter-1.2.2.linux-amd64.tar.gz node_exporter-1.2.2.linux-amd64

EXPOSE 9100

CMD ["node_exporter", "--path.procfs=/host/proc", "--path.sysfs=/host/sys", "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)"]
