FROM google/cadvisor:v0.38.5
ENV CADVISOR_ARGS="--storage_driver=db2 --collector=cpu --collector=memory --collector=diskstats"
RUN adduser --system --no-create-home --disabled-password --group nonroot
USER nonroot
HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 CMD curl --fail http://localhost:8080/healthz || exit 1
EXPOSE 8081
CMD ["--port=8081", "--docker_only=true", ${CADVISOR_ARGS}]
