
version: '3.7'
 
services:
    react-app:
        build:
            context: .
            dockerfile: Dockerfile-dev
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - '3000:3000'
            - '4200:4200'
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true
    