---
- name: Copy Backup from Docker Container to Local Server
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get a list of running containers
      docker_container_info:
        state: present
      register: docker_containers
      changed_when: false

    - name: Extract container names from the result
      set_fact:
        container_names: "{{ docker_containers.containers | map(attribute='Names') | list }}"

    - name: Debug container names
      debug:
        var: container_names

    - name: Copy backup from each container to local server
      docker_copy:
        name: "{{ item }}"
        src: /var/www/html/  # Source directory within the container
        dest: /var/www/html/{{ item }}.tar.gz
        content: yes
      with_items: "{{ container_names }}"
