# Use Ubuntu as the base image
FROM ubuntu:latest

# Install and configure your application (adjust based on your requirements)
# Example: Install necessary dependencies and copy application files
RUN apt-get update && \
    apt-get install -y nginx && \
    rm -rf /var/lib/apt/lists/*

# Copy your Nginx configuration files and application files
# COPY app1/nginx.conf /etc/nginx/nginx.conf
COPY app3/index.html /var/www/html/

# Expose the necessary ports
EXPOSE 8084

# CMD instruction to start your application
CMD ["nginx", "-g", "daemon off;"]